policy_path: "./model/policy_4.pt"
# xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/zsl1/scene.xml"
#resources/robots/galileo/scene_staris.xml
#resources/robots/zsl-1/scene.xml
# Total simulation time
# Total simulation time
simulation_duration: 360.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

# kps: [28.0, 28.0, 28.0, 28.0, 28.0, 28.0, 28.0, 28.0, 28.0, 28.0, 28.0, 28.0] 
# kds: [0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7, 0.7] 
kps: [40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0, 40.0] 
kds: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0] 


default_angles: [0.1,  0.65,  -1.5,  -0.1,  0.65,  -1.5, 
                 0.1,  1.1,  -1.5,  -0.1,  1.1,  -1.5] 


# lin_vel_scale: 2.0
# ang_vel_scale: 0.25 
# dof_pos_scale: 1.0 
# dof_vel_scale: 0.05 
# action_scale: 0.25
# cmd_scale: [2.0, 2.0, 0.25]

lin_vel_scale: 2.0
ang_vel_scale: 0.25 
dof_pos_scale: 1.0 
dof_vel_scale: 0.05 
action_scale: 0.25
cmd_scale: [1.5, 1.5, 0.4]
num_actions: 12
num_obs: 270
num_one_step_obs: 45

cmd_init: [0, 0, 0]
